name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and deploy
        run: |
          ./mvw clean package
          cp target/*.jar $GITHUB_WORKSPACE/app.jar
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -B gh-pages
          git add -f app.jar
          git commit -m "Deploy application"
          git push -f origin gh-pages
