# maven.yml
name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (skip tests)
        run: mvn -B package -DskipTests --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t mboup1/app-ci-cd-github-spring-boot:latest .
          docker push mboup1/app-ci-cd-github-spring-boot:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#      - name: Deploy Docker container to server
#        run: |
#          ssh user@yourserver.com 'docker pull mboup1/app-ci-cd-github-spring-boot:latest'
#          ssh user@yourserver.com 'docker stop app-ci-cd-github-spring-boot || true && docker rm app-ci-cd-github-spring-boot || true'
#          ssh user@yourserver.com 'docker run -d --name app-ci-cd-github-spring-boot -p 8080:8080 mboup1/app-ci-cd-github-spring-boot:latest'
